### PR TITLE
127 level support and fixes for non-nested runs

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description of changes
1. parm/WaterInTheWestL128.conf overrides configuration parameters to run with 128 levels (127 mass, 128 interface)
2. Correct errors in a few parm files that corrupted the inputs to non-nested global runs
3. Allow output frequencies other than three-hourly
4. Update to Rocoto 1.3.6. The prior version no longer runs (sysadmins disabled it).

### GAEA Troubles

Although the code compiles and the model runs, the UPP cannot run. It freezes in MPI_Finalize for some inputs. There is an open ticket with GFDL for this.

### Hera pygraf troubles

After the transition to Rocky, pygraf is no longer able to run:

```
Traceback (most recent call last):
  File "./create_graphics.py", line 733, in <module>
    create_graphics(sys.argv[1:])
  File "./create_graphics.py", line 729, in create_graphics
    graphics_driver(CLARGS)
  File "/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/rocky-l128/sorc/hafs_graphics.fd/pygraf/adb_graphics/utils.py", line 329, in wrapper_timer
    value = func(*args, **kwargs)
  File "./create_graphics.py", line 618, in graphics_driver
    gribfiles = gather_gribfiles(cla, fhr, grib_path, gribfiles)
  File "./create_graphics.py", line 119, in gather_gribfiles
    gribfiles = gribfile.GribFiles(
  File "/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/rocky-l128/sorc/hafs_graphics.fd/pygraf/adb_graphics/datahandler/gribfile.py", line 58, in __init__
    self.grid_suffix = self._get_grid_suffix(filenames)
  File "/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/rocky-l128/sorc/hafs_graphics.fd/pygraf/adb_graphics/datahandler/gribfile.py", line 185, in _get_grid_suffix
    gfile = xr.open_dataset(files[0],
  File "/contrib/miniconda3/4.5.12/envs/pygraf/lib/python3.8/site-packages/xarray/backends/api.py", line 513, in open_dataset
    store = backends.NioDataStore(filename_or_obj, lock=lock, **backend_kwargs)
  File "/contrib/miniconda3/4.5.12/envs/pygraf/lib/python3.8/site-packages/xarray/backends/pynio_.py", line 48, in __init__
    import Nio
  File "/contrib/miniconda3/4.5.12/envs/pygraf/lib/python3.8/site-packages/PyNIO/Nio.py", line 83, in <module>
    from _nio import *
ImportError: libnsl.so.1: cannot open shared object file: No such file or directory
```

## Issues addressed (optional)
None

## Dependencies (optional)
None

## Contributors (optional)
Ning Wang

## Tests conducted
Ran a C384 case in many different configurations and confirmed inputs were as expected.
Ran C96, C192, C384, and C768 with 128 levels and 65 levels to see if they worked.
Added a WaterInTheWestL128C768.conf file which overrides task geometry and node count so a 120 hour forecast finishes in under 8 hours on Hera.

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
This Issue tracks the process of resurrecting GAEA C5 support:

https://github.com/ufs-community/ufs-weather-model/issues/2101-

**Comment by SamuelTrahanNOAA** [comment]
This branch crashes when I run 127 levels with a nest at C768.

If you take out any of those three conditions, it runs. For example, run at 65 levels, or disable the nest, or run at C384. Any one of those changes will let it run. It's only the high resolution nested case that fails.

I have a staged test case here. It is not in a workflow; it's just a directory where you can resubmit a `job.sh`:

```
/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/crashing-nested-l127c768-righttau
```

The `job.sh` script in that directory will run the test case. Be sure to edit the `base=` line to point to your source code:

In the workflow, to run with 127 levels, you must use this conf= line in rocoto/WaterInTheWest.sh:

```bash
conf="../parm/WaterInTheWest.conf ../parm/WaterInTheWestL128.conf"
```

If you want to run the uniform C768, you can add `../parm/WaterInTheWestC768Uniform.conf`, or to run the stretched rotated globe without its nest, `../parm/WaterInTheWestC768NoNest.conf`

**Comment by SamuelTrahanNOAA** [comment]
The model does not crash with this version and I get only four Warn_K messages (instead of >13000). The inline post is crashing, possibly due to an out-of-memory issue.

/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/crashing-nested-l127c768-tweaks

The changes are:

- n_split is 5, matching GFS and RRFS
- 75s timestep instead of 60
- hord and kord for the globe match GFS
- dt_atmos = dt_inner
- hord and kord for the nest match RRFS
- k_split = 1 for the global and 4 for the nest. This means:
    - `dt_atmos/k_split` for the globe is 75s, matching GFS
    - `dt_atmos/k_split` for the nest is 18.75s, close to RRFS's 18s
    - The nest:global refinement ratio (4) is the same as the nest:global ratio of `k_split` (4)

With all of these changes, it seems to work. The runtime is far too long, though. I expect the resource balance between nest and globe has changed, so I will try to get some speed back from tweaking the layouts.

**Comment by lisa-bengtsson** [comment]
Great work Sam!

**Comment by SamuelTrahanNOAA** [comment]
Unfortunately, the inline post is still crashing, and it looks like an out of memory issue. I'm updating the workflow to run this new configuration and I'll try it with an offline post instead. (inline = run post in the model; offline = run post outside the model)

**Comment by SamuelTrahanNOAA** [comment]
The quilt servers now need 300 MPI ranks on Hera to store the grid. To run the inline post, they need 480 MPI ranks. This increase makes sense. We doubled the number of vertical levels, so now we need more memory to store the grid.

This means the quilt servers now take about 1/3 of the resources (960 MPI ranks out of 3300).

**Comment by lisa-bengtsson** [comment]
Hi Sam, can we use top of develop code for the executable in your sandbox?

**Comment by SamuelTrahanNOAA** [comment]
I'm using what was the top of develop when I started debugging this. I'll update again in my next test.

**Comment by SamuelTrahanNOAA** [comment]
I got back much of the speed by doing this:

1. Update to the latest ufs-weather-model
2. Compile with -DFASTER=ON
3. Use zstd instead of zlib compression.

It's still disproportionately slower than the 65 level version. A different balance of nest vs. global computational cost would cause that. I'll try tweaking that next.

**Comment by SamuelTrahanNOAA** [comment]
I have lots of other tweaks to speed it up. Now a 24 hour forecast takes 130 minutes on 150 Hera nodes.

**Comment by SamuelTrahanNOAA** [comment]
I'm not sure it's possible to do a five-day forecast with this configuration on Hera, but I'm about to try. With 210 nodes, I think it'll finish in about seven and half hours. We'll see.

**Comment by SamuelTrahanNOAA** [comment]
It worked, sortof. I did a five day forecast in seven hours with 210 nodes, but I had to disable model history output. That means you get restart files and GRIB files, but no model netcdf output.

I also compiled with -DFASTER=ON and the latest code. Both of those changes will affect results.

**Comment by AndersJensen-NOAA** [comment]
@SamuelTrahanNOAA good to hear that it sort of worked. Can you add more nodes for io or more write_tasks so that we can have netcdf output?

**Comment by SamuelTrahanNOAA** [comment]
> good to hear that it sort of worked. Can you add more nodes for io or more write_tasks so that we can have netcdf output?

I cannot add more nodes on Hera. If I move nodes from compute to I/O, it won't finish a five day forecast in under 8 hours. You could have netcdf output if you run fewer than five days.

**Comment by AndersJensen-NOAA** [comment]
> > good to hear that it sort of worked. Can you add more nodes for io or more write_tasks so that we can have netcdf output?
> 
> I cannot add more nodes on Hera. If I move nodes from compute to I/O, it won't finish a five day forecast in under 8 hours. You could have netcdf output if you run fewer than five days.

Okay, thanks. I'll look at the results when I get a chance -- let me know where the output is located.

**Comment by SamuelTrahanNOAA** [comment]
> Okay, thanks. I'll look at the results when I get a chance -- let me know where the output is located.

I'm trying a new configuration that might work. I'll let you know later

**Comment by SamuelTrahanNOAA** [comment]
I was able to get netcdf output, but only three hourly.

/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/crashing-nested-l127c768-with-output

If you want hourly output on hera, there'll be no netcdf files.

The scripts won't do this yet. I'm working on that.

EDIT: It took about 7.8 hours. That means random runtime variability will be enough to push it over 8 hours, which is the maximum wallclock limit on Hera. You can do a 4.5 day forecast with good reliability.

**Comment by SamuelTrahanNOAA** [comment]
There is now a parm/WaterInTheWestL128C768.conf which can override the WaterInTheWest.conf to run 127 levels correctly. Use it by modifying the WaterInTheWest.sh conf line to send both files:

```bash
conf="../parm/WaterInTheWest.conf ../parm/WaterInTheWestL128C768.conf"
```

A 4.5 day forecast should finish reliably in eight hours. A 5 day forecast might finish in eight hours.

**Comment by lisa-bengtsson** [comment]
Hi Sam,

In your staged test here: /scratch2/BMC/wrfruc/Samuel.Trahan/westwater/crashing-nested-l127c768-righttau which namelists are used? I see you have: input_nest02.nml, input_nest.nml.tmp, input.nml,  input.nml.tmp? 

It looks like you have shallow convection from C3 active in this setup, but in our previous correspondence we had decided to use MYNN shallow cu. But I may be looking in the wrong namelist? 

Thanks!

**Comment by SamuelTrahanNOAA** [comment]
The relevant namelists are input.nml (global) and input_nest02.nml (nest). All the "*.tmp" files are templates. Could you give me corrected namelists? I will update the scripts accordingly.

**Comment by lisa-bengtsson** [comment]
> The relevant namelists are input.nml (global) and input_nest02.nml (nest). All the "*.tmp" files are templates. Could you give me corrected namelists? I will update the scripts accordingly.

Thanks Sam, me and @egrell will take a look tomorrow, I'm still a bit uncertain on some of the iopt settings we discussed with Mike Barlage, but shallow cu should be turned off, and we should remove it also from the global_nest_v1 SDF. We will have more exact updates tomorrow. Thanks

**Comment by SamuelTrahanNOAA** [comment]
> we should remove it also from the global_nest_v1 SDF

We can't change the suite definition file in this PR. Whatever change you make now must work with the current code.

**Comment by lisa-bengtsson** [comment]
@egrell took a look and there are two flags we are uncertain about.

shal_cnv and iopt_sfc

We ultimately want to turn off C3 shallow convection and use MYNN shallow convection. I believe you can still have shallow convection as a scheme in the SDF, but turn it off via namelist. If we did it this way, we are uncertain if it is enough to set shal_cnv = false, or if we also need to set imfshalcnv = 0. Evelyn is looking into it. A better solution would probably be to create a PR in the ufs-weather-model to update the global_nest_v1 SDF file to not include shallow convection. 

Currently iopt_sfc = 4 in your namelist, but I recall from our discussions with @barlage and @joeolson42 that iopt_sfc should be 3? Did you guys have a chance to look into this?

**Review by AndersJensen-NOAA — APPROVED** [review]

**Review by lisa-bengtsson — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
This is as ready as it will ever be. If I don't hear any objections soon, I'll merge it.

There are two outstanding issues which are unrelated to these changes. I mention them in the PR description, and I'll open issues soon.

**Comment by AndersJensen-NOAA** [comment]
> This is as ready as it will ever be. If I don't hear any objections soon, I'll merge it.
> 
> There are two outstanding issues which are unrelated to these changes. I mention them in the PR description, and I'll open issues soon.

Thanks @SamuelTrahanNOAA.

**Comment by lisa-bengtsson** [comment]
> > This is as ready as it will ever be. If I don't hear any objections soon, I'll merge it.
> > There are two outstanding issues which are unrelated to these changes. I mention them in the PR description, and I'll open issues soon.
> 
> Thanks @SamuelTrahanNOAA.

I agree, thanks Sam - it is impressive work.

**Comment by SamuelTrahanNOAA** [comment]
Apparently I cannot open issues in this repository. I'll open them in other repositories.

**Pull request merged**
