### PR TITLE
C96 support on GAEA and some namelist corrections

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
## Description of changes
1. C96 support works again. It uses the global_nest_v1 suite. I hope the settings are correct for C96; I copied them from Lisa's and Mike's emails.
2. The rf_cutoff is now 10 for all resolutions.
3. I fixed a minor problem in WaterInTheWest.conf (the C768 configuration). It used the C1536 settings for a few variables. This didn't affect anything because the C768 and C1536 settings were the same. However, that may change in the future. It should point to the right variables.

## Issues addressed (optional)
None

## Dependencies (optional)
None

## Contributors (optional)
If others worked on this PR besides the author, please include their user names here (using @Mention if possible).

## Tests conducted
C96 on Hera and GAEA

### CODE REVIEW

**Review by mdtoyNOAA — APPROVED** [review]

**Review by mdtoyNOAA — COMMENTED** [review]
@SamuelTrahanNOAA   I approved these changes about 45 minutes ago, but on second glance, I noticed that 'rf_cutoff' is set to 1.0.  We have been testing with 'rf_cutoff=10.0'.  This is the latest recommendation by the dycore folks, e.g., Xiaqiong Zhou and Kevin Viner.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA I approved these changes about 45 minutes ago, but on second glance, I noticed that 'rf_cutoff' is set to 1.0. We have been testing with 'rf_cutoff=10.0'. This is the latest recommendation by the dycore folks, e.g., Xiaqiong Zhou and Kevin Viner.

Should that be the same for all resolutions?

**Comment by mdtoyNOAA** [comment]
> > @SamuelTrahanNOAA I approved these changes about 45 minutes ago, but on second glance, I noticed that 'rf_cutoff' is set to 1.0. We have been testing with 'rf_cutoff=10.0'. This is the latest recommendation by the dycore folks, e.g., Xiaqiong Zhou and Kevin Viner.
> 
> Should that be the same for all resolutions?

Yes.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA I approved these changes about 45 minutes ago, but on second glance, I noticed that 'rf_cutoff' is set to 1.0. We have been testing with 'rf_cutoff=10.0'. This is the latest recommendation by the dycore folks, e.g., Xiaqiong Zhou and Kevin Viner.

I've made this change on GAEA and I'm retesting now.

**Comment by SamuelTrahanNOAA** [comment]
@mdtoyNOAA 

Before I make any more changes, could you please thoroughly check the namelists to determine if they're right?
On HERA, here are the nested configurations' forecast directories:

- /scratch2/BMC/wrfruc/Samuel.Trahan/westwater/scrub/checkc96/2023022400/00L/forecast/
- /scratch2/BMC/wrfruc/Samuel.Trahan/westwater/scrub/psigC192/2023022400/00L/forecast/
- /scratch2/BMC/wrfruc/Samuel.Trahan/westwater/scrub/psigC384/2023022400/00L/forecast/
- /scratch2/BMC/wrfruc/Samuel.Trahan/westwater/scrub/psigC768/2023022400/00L/forecast/

These are the non-nested ones:

- /scratch2/BMC/wrfruc/Samuel.Trahan/westwater/scrub/psigUniform/2023022400/00L/forecast/
- /scratch2/BMC/wrfruc/Samuel.Trahan/westwater/scrub/psigNoNest/2023022400/00L/forecast/

**Comment by SamuelTrahanNOAA** [comment]
The rf_cutoff is now 10 for all resolutions.

**Comment by mdtoyNOAA** [comment]
@SamuelTrahanNOAA  The namelists you sent me are all 100% correct regarding the gravity wave drag (GWD) settings in the _&gfs_physics_nml_ namelist.  However, I don't want to speak to the Rayleigh damping settings (e.g., rf_cutoff) in the &fv_core_nml namelist.  I didn't have anything to do with the development of these variables, however, I was involved with their testing.  There are two cases to consider -- "high-top" models (e.g., 127level FV3GFS) and "low-top" models (e.g., RRFS and HAFS).  I have no idea whether the HAFS configuration for AF is high- or low-top.  You'll need to get clarification on this.  

Here is what I heard from Fanglin Yang today:
"If implicit rayleigh damping is used (like HR3), cutoff should be set to 10 Pa.
It is recommended for low-top models (RRFS and HAFS), the "old" explicit Rayleigh damping should be used."

Here's what it means for the input.nml -- &fv_core_nml settings:

For "High-top" models:
  tau = 0.   (this "turns off" the "old" explicit Rayleigh damping)
  rf_cutoff = 10.
  fast_tau_w_sec = 0.2  (this variable is for the "new" implicit Raleigh damping)

For "Low-top" models:
  tau = 10.   (this "turns on" the "old" explicit Rayleigh damping)
  rf_cutoff = 7.5e2
Note: With the "old" explicit Rayleigh damping, there was no "fast_tau_w_sec" variable.

**Comment by SamuelTrahanNOAA** [comment]
We're using 65 levels, but I don't know the model top.

**Comment by SamuelTrahanNOAA** [comment]
@mdtoyNOAA Model top is 20 Pa. That's pretty high up. Is the rf_cutoff=10 okay?

```
forecast.log: 96:  Nested grid   2,  ptop =    20.00 Pa
forecast.log: 96:  Parent grid   2,  ptop =    20.00 Pa
```

**Comment by mdtoyNOAA** [comment]
@SamuelTrahanNOAA  Let's just pick the "old" explicit Rayleigh damping as used in RRFS for the PR, i.e.,
	tau = 10.
	rf_cutoff = 750.
	fast_tau_w_sec = 0.

Then we can test the "new" implicit Rayleigh damping later for comparison and issue a new PR if necessary at a later date.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA Let's just pick the "old" explicit Rayleigh damping as used in RRFS for the PR, i.e., tau = 10. rf_cutoff = 750. fast_tau_w_sec = 0.
> 
> Then we can test the "new" implicit Rayleigh damping later for comparison and issue a new PR if necessary at a later date.

Have you looked at the namelist files? Do we need to change anything else?

**Comment by mdtoyNOAA** [comment]
> > @SamuelTrahanNOAA Let's just pick the "old" explicit Rayleigh damping as used in RRFS for the PR, i.e., tau = 10. rf_cutoff = 750. fast_tau_w_sec = 0.
> > Then we can test the "new" implicit Rayleigh damping later for comparison and issue a new PR if necessary at a later date.
> 
> Have you looked at the namelist files? Do we need to change anything else?

Yes, I have looked at them and I don't see anything else that needs to be changed.

**Comment by SamuelTrahanNOAA** [comment]
@mdtoyNOAA - Are the settings correct now?

This is the C192:

/scratch2/BMC/wrfruc/Samuel.Trahan/westwater/scrub/rf750atC192/2023022400/00L/forecast/

I'm rerunning the other resolutions now.

**Comment by mdtoyNOAA** [comment]
> @mdtoyNOAA - Are the settings correct now?
> 
> This is the C192:
> 
> /scratch2/BMC/wrfruc/Samuel.Trahan/westwater/scrub/rf750atC192/2023022400/00L/forecast/
> 
> I'm rerunning the other resolutions now.

Yes, the settings look correct.

**Pull request merged**
